apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: avn5d50uj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: avn5d50uj-python 
  name: avn5d50uj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: avn5d50uj-python 
